!function(e){var n={};function s(t){if(n[t])return n[t].exports;var r=n[t]={i:t,l:!1,exports:{}};return e[t].call(r.exports,r,r.exports,s),r.l=!0,r.exports}s.m=e,s.c=n,s.d=function(e,n,t){s.o(e,n)||Object.defineProperty(e,n,{enumerable:!0,get:t})},s.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},s.t=function(e,n){if(1&n&&(e=s(e)),8&n)return e;if(4&n&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(s.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&n&&"string"!=typeof e)for(var r in e)s.d(t,r,function(n){return e[n]}.bind(null,r));return t},s.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return s.d(n,"a",n),n},s.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},s.p="",s(s.s=0)}({"./competencias2023/blink-src/js/cke_styles.js":
/*!*****************************************************!*\
  !*** ./competencias2023/blink-src/js/cke_styles.js ***!
  \*****************************************************/
/*! exports provided: default */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\n/*\r\n*   Array con la definición de los estilos para el editor de CKEditor\r\n*/\nconst ckeStyles = [{\n  name: 'Caja 1',\n  type: 'widget',\n  widget: 'blink_box',\n  attributes: {\n    'class': 'box-1'\n  }\n}, {\n  name: 'Caja 2',\n  type: 'widget',\n  widget: 'blink_box',\n  attributes: {\n    'class': 'box-2'\n  }\n}, {\n  name: 'Énfasis',\n  element: 'span',\n  attributes: {\n    'class': 'bck-enfasis'\n  }\n}];\n/* harmony default export */ __webpack_exports__[\"default\"] = (ckeStyles);\n\n//# sourceURL=webpack:///./competencias2023/blink-src/js/cke_styles.js?")},"./competencias2023/blink-src/js/main.js":
/*!***********************************************!*\
  !*** ./competencias2023/blink-src/js/main.js ***!
  \***********************************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _cke_styles__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./cke_styles */ "./competencias2023/blink-src/js/cke_styles.js");\n/* harmony import */ var _overrides__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./overrides */ "./competencias2023/blink-src/js/overrides.js");\n/*\r\n*   Javascript principal con la estructura básica del estilo\r\n*/\n\n\n\n(function (blink) {\n  \'use strict\';\n\n  var Competencias2023Style = function () {\n    blink.theme.styles["generic2022"].apply(this, arguments);\n  };\n\n  Competencias2023Style.prototype = {\n    parent: blink.theme.styles["generic2022"].prototype,\n    bodyClassName: \'content_type_clase_competencias2023\',\n    extraPlugins: [\'image2\'],\n    ckEditorStyles: {\n      name: \'competencias2023\',\n      styles: _cke_styles__WEBPACK_IMPORTED_MODULE_0__["default"]\n    },\n    init: function () {\n      // Heredo de otro estilo\n      this.parent.init.call(this.parent, this);\n      this.removeFinalSlide();\n    },\n    ..._overrides__WEBPACK_IMPORTED_MODULE_1__["default"]\n  };\n  Competencias2023Style.prototype = _.extend({}, new blink.theme.styles["generic2022"](), Competencias2023Style.prototype);\n  blink.theme.styles[\'competencias2023\'] = Competencias2023Style;\n})(blink);\n\n//# sourceURL=webpack:///./competencias2023/blink-src/js/main.js?')},"./competencias2023/blink-src/js/overrides.js":
/*!****************************************************!*\
  !*** ./competencias2023/blink-src/js/overrides.js ***!
  \****************************************************/
/*! exports provided: default */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/*\r\n*   Javascript donde están las funciones que sobreescriben a funciones de Basic\r\n*/\nconst overrides = {\n  removeFinalSlide: t => {\n    let thisStyle = blink.activity.currentStyle;\n    thisStyle.parent.removeFinalSlide.call(thisStyle.parent, thisStyle, true);\n  }\n};\n/* harmony default export */ __webpack_exports__["default"] = (overrides);\n\n//# sourceURL=webpack:///./competencias2023/blink-src/js/overrides.js?')},"./competencias2023/blink-src/styles/main.scss":
/*!*****************************************************!*\
  !*** ./competencias2023/blink-src/styles/main.scss ***!
  \*****************************************************/
/*! no static exports found */function(module,exports,__webpack_require__){eval("// extracted by mini-css-extract-plugin\n    if(false) { var cssReload; }\n  \n\n//# sourceURL=webpack:///./competencias2023/blink-src/styles/main.scss?")},0:
/*!***************************************************************************************************!*\
  !*** multi ./competencias2023/blink-src/js/main.js ./competencias2023/blink-src/styles/main.scss ***!
  \***************************************************************************************************/
/*! no static exports found */function(module,exports,__webpack_require__){eval('__webpack_require__(/*! D:\\workspaces\\web\\blinkweb\\blink\\www\\themes\\responsive\\assets\\styles\\competencias2023\\blink-src\\js\\main.js */"./competencias2023/blink-src/js/main.js");\nmodule.exports = __webpack_require__(/*! D:\\workspaces\\web\\blinkweb\\blink\\www\\themes\\responsive\\assets\\styles\\competencias2023\\blink-src\\styles\\main.scss */"./competencias2023/blink-src/styles/main.scss");\n\n\n//# sourceURL=webpack:///multi_./competencias2023/blink-src/js/main.js_./competencias2023/blink-src/styles/main.scss?')}});